name: Deploy GAS WebApp

env:
  AZURE_APP_NAME: 'gas-web'    
  DOTNET_VERSION: '6.0.x'
  PROJECT_PATH: './WebApp/WebApp.csproj'
  TRIGGER_PATH: 'WebApp/**'

on:
  push:
    branches:
      - main
    paths: 
      - ${{env.TRIGGER_PATH}}
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}
      
      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build with dotnet
        run: dotnet build -c Release ${{env.PROJECT_PATH}}

      - name: Publish with dotnet
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/release ${{env.PROJECT_PATH}}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: ${{env.DOTNET_ROOT}}/release

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: release

      - name: Deploy to GAS WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_APP_NAME}}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
